name: Release

on:
  push:
    branches: [master, alpha, beta]

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Compile TypeScript
        run: npm run build
      - name: Test
        run: npm test
      - name: Release
        env:
          GIT_AUTHOR_NAME: Eric Crosson
          GIT_AUTHOR_EMAIL: eric.s.crosson@utexas.edu
          GIT_COMMITTER_NAME: Eric Crosson
          GIT_COMMITTER_EMAIL: eric.s.crosson@utexas.edu
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
